version: '2'
networks:
    main:
services:
    vpn:
        image: kylemanna/openvpn:2.1.0
        volumes:
            - /home/openvpn/data:/etc/openvpn
        cap_add:
            - NET_ADMIN
        ports:
            - "443:1194/udp"
            - "1194:1194/udp"
            - "1194:1194/tcp"
